### ISSUE TITLE
Joining the models

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#10]
@davidwhogg can you please read through the description in the manuscript for how the models are joined, and give your opinion on the following items:
- [ ] the nomenclature
- [ ] whether we should fit `\delta_{teff,ms}`, `\delta_{teff,logg}`, etc
- [ ] is any of the terminology obviously wrong?
- [ ] is there a better method that you would recommend we try?

**Comment by andycasey** [comment]
And comment on the fact of showing individual abundances for objects with `w_ms < 0.05` (e.g., not `w_ms = 0`). I want to hear all opinions, strong or otherwise.

**Comment by davidwhogg** [comment]
I am fine with all of the choices, including the 0.05 choice.

I think the section should both begin and end with a statement to the effect that our choices here are heuristic, and depart from the program of keeping The Cannon outputs as the maxima of various individual likelihood functions. We perform the combination treating The Cannon as producing estimates of labels, and use those estimates to produce a unified estimate. but without regard (any more) to the probabilistic justification.

Or something like that. Put in words to this effect and then you can close this.

**Comment by andycasey** [comment]
Fixed in 8a55302.
