### ISSUE TITLE
Metal-poor abundances

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#13]
For the giant star training set we were forced to include very metal-poor stars from Ruchti, Fulbright, etc so that our abundances didn't taper off at the edge of the training set. However, we didn't readily have individual abundances for those stars, so I just guessed them to follow galactic chemical evolution (e.g., [alpha/Fe] ~ +0.4).

It turns out that was a really _bad_ thing to do, because now all metal-poor stars in that regime end up with those values. You can see this structure in the galactic chemical evolution plot.

We either need to: 
- collate individual abundances of (O, Mg, Al, Si, Ca, Ni) from the literature for those metal-poor stars (heterogenous sources are OK, we just need to keep track of where things came from -- it is more important for us to be able to identify stars with [Fe/H] ~ -4);
- admit that our individual abundances for extremely metal-poor giants are probably all wrong (and perhaps, remove the individual abundances for stars below [Fe/H] ~ -2); or,
- initialise them with random values around the central values we have already adopted.

Given time constraints, we probably cannot run too many experiments, because the analysis of 500,000 spectra with a 9 label regularized model takes about ~6 hours or so in wall clock time, unless I branch out to other CPU resources (which is possible).

I want discussion on this amongst co-authors. @mkness @davidwhogg @HWRix @keithhawkins @amkunder thoughts?

**Comment by andycasey** [comment]
And @amkunder!

**Comment by davidwhogg** [comment]
I am in favor of admitting and flagging and moving on. At this stage we can't extend scope

**Comment by davidwhogg** [comment]
Ps we can explicitly flag any star at or beyond our safe zone

**Comment by keithhawkins** [comment]
I agree with Hogg. To obtain results+paper by Gaia release we will need to
limit somewhat the scope. I would be worried about using heterogeneous
sources unless we can prove that they are systematically in line with the
primary source we are taking the labels from.

It may be worth exploring this later though.

**Comment by andycasey** [comment]
I've admitted that our individual abundances for extremely metal-poor giants are probably all wrong. There will either be a `QC` flag and `QC_ABUNDANCES` that indicates whether results are knowingly erroneous or not, or I will just remove those results which I don't believe.
