### ISSUE TITLE
Multiple entries in PASTEL database

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#2]
Of the 4,672 entries in the PASTEL database, 3,865 entries are duplicates of the same star. Some stars have >50 entries. For this comparison we should cull down to just compare against a few large samples, or go through and select the "best" value for each star.

This affects the file in `article/figures/plot_literature_comparison.py`

**Comment by davidwhogg** [comment]
!

**Comment by andycasey** [comment]
Kordopatis has sent me a distilled set of acceptable literature comparisons that were used in his DR4 paper.
