### ISSUE TITLE
Use correct Pleiades isochrone

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#26]
We are using one isochrone, then we say that the discrepancy is because isochrones don't fit young clusters. But we specifically cite one study that _produces_ an isochrone for this cluster.

Use that one in our figures instead.

**Comment by keithhawkins** [comment]
The empirical isochrones from that source seems to be only in the photometric filters (thus no Teff, log g values). Additionally, I have checked the empirical isochrones http://www.astronomy.ohio-state.edu/iso/pl.html http://www.astronomy.ohio-state.edu/iso/pl.html also doesn’t seem to work very well.
