### ISSUE TITLE
Define common set of quality constraints

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#6]
For "believable" stellar parameters and chemical abundances.

Some statistics of use: `snr`, `R` (correlation coefficient from the RAVE pipeline), `r_chi_sq`.

The same quality cut should then be applied for stars in all figures.

**Comment by keithhawkins** [comment]
Is there a new copy of the table to star looking at the combination of these parameters giving believable results?

**Comment by andycasey** [comment]
There is (`unrave-v0.7*`), but it is a little complicated at the moment because I am not convinced that the main-sequence and the giant models have been joined correctly. They are joined correctly in the sense that the H-R diagram looks great, but it is clear that there are issues. For example, the results for metal-poor dwarfs are being taken from the giant model.

When I make comparison plots (e.g., to Bensby, etc) and just use the main-sequence model, then everything looks great. Similarly when I plot the galactic chemical evolution of individual abundances from the giant stars. But when using the joint model, there are systematic effects.

**Comment by andycasey** [comment]
Defined as `S/N > 10` and `\chi_r^2 < 3`, since those constraints make all the literature comparisons look good, and there isn't much further we could go in S/N..
