### ISSUE TITLE
MP dwarfs at ~4000 K

### ISSUE THREAD

**Issue by andycasey** [AnnieJumpCannon/RAVE#7]
There are anomalous dwarf stars at Teff ~ 4000 K that have [Fe/H] ~ -0.2. Something is wrong with their spectra and they've been projected into that part of the label space.

Understand and remove.

**Comment by andycasey** [comment]
Ken Freeman's comments makes me think this could be due to fringing. Either way, we should see whether artefacts like this are removed with the use of morphological classifications from Matejvic, and if so, just recommend caution before submitting to Nature based on some spurious looking artefact.

**Comment by davidwhogg** [comment]
Make sure the "submitting to Nature" phrasing makes it into the text!
